### ISSUE TITLE
SSL Doesn't support

### ISSUE THREAD

**Issue by sonuyos** [muety/website-watcher#1]
Hello,

Your code does not support SSL?

It is giving out error.

requests.exceptions.SSLError: HTTPSConnectionPool(host='XXXXXX.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '_ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure'),))

**Comment by muety** [comment]
Sorry, although it's two and and a half years later now, can somebody still reproduce this problem? I can't, unfortunately.
