### ISSUE TITLE
Add possibility to monitor a list of URLs instead of single URL

### ISSUE THREAD

**Issue by coveritytest** [muety/website-watcher#15]
It would be nice, if you could add a file with a list of URLs that get checked instead of a single URL.

**Comment by muety** [comment]
Good idea! How would you want to proceed with tolerance and XPath parameters? Would you suggest to configure them separate for each URL (see below) or globally for all? What would be appropriate for your use case?

```
# (url, tolerance, xpath)
https://url1.com, 75, //body
https://url2.com, 0, //div[name="article-container"]
...
```

**Comment by coveritytest** [comment]
Separate for each URL would be nice of course :) What do you think of json as input?

```
{
  "url_list": [
    {
      "url": "https://url1.com",
      "tolerance": 75,
      "xpath": "body"
    },
    {
      "url": "https://url2.com",
      "tolerance": 0,
      "xpath": "div[name="article-container"]"
    }
  ]
}
```

**Comment by muety** [comment]
A JSON-formatted scrape config like the one you suggested seems to be a good option. 

I'm thinking about keeping the logic for performing multiple scrapes outside of the actual watcher and provide a Bash script instead. It would read JSON config, iterate the array of URLs and parameters and call `watcher.py` for each entry. Doing so wouldn't add additional complexity to the actual code and have control logic separated from business logic. The only drawback would be the fact that Windows users wouldn't be able to use that functionality unless we also provide a Batch- or PowerShell script.

**Comment by coveritytest** [comment]
Yeah that's a good point, might be better to do it this way.
