### ISSUE TITLE
Predicting Tolerance

### ISSUE THREAD

**Issue by kaushalvivek** [muety/website-watcher#2]
How about embedding a light-weight statistical model that can study a website for say, an hour, generate enough data to predict a suitable tolerance score to automatically detect changes?

**Comment by n1try** [comment]
Sounds a bit like overkill to me, but if somebody feels like adding such a feature, it'd be welcome!
In any case, I agree that this script could need some more advanced techniques / heuristics to detect a change. I opened #3.
