### ISSUE TITLE
Bug in batch.sh

### ISSUE THREAD

**Issue by coveritytest** [muety/website-watcher#22]
I don't know why yet, but when using

`"xpath": "//div[@class='l-splitpage-content position-relative srpold']",`

in example/many.json, batch.sh crashes.

**Comment by muety** [comment]
Thanks for that bug report. I'll take a look.

**Comment by coveritytest** [comment]
It seems to be problem with jq's handling of single quotes.

**Comment by coveritytest** [comment]
Found the reason, it's in https://github.com/muety/website-watcher/blob/master/batch.sh#L27. The for loop is working with spaces, and if there is a space in the JSON itself, it won't work.

**Comment by muety** [comment]
I think I fixed it, please check. 

Thanks for pointing me in the right direction with your hint. Bash is weird...

**Comment by coveritytest** [comment]
Great, thanks for the fix. There is another problem, though. You put double quotes around the variables in line https://github.com/muety/website-watcher/blob/master/batch.sh#L57. Problem with `$ignore` is, that Python's argparse expects multiple arguments in the form `-i arg1 arg2` or `-i 'arg1' 'arg2'`. Currently it's `-i 'arg1 arg2'` which results in one single XPath expression instead of a list.

**Comment by muety** [comment]
I see the problem. Probably those quotes aren't even needed anyway. We can probably remove them again.

**Comment by coveritytest** [comment]
I guess you can keep the double quotes in line 57, except for `$ignore`, just checked it, seems to work.
